### ISSUE TITLE
Font-awesome icons are not showing

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#122]
All FA icons are showing up as boxes on production child and news:

Not showing:
http://libraries.mit.edu/news/subscribe/
http://libraries.mit.edu/giving/

Showing:
http://libraries.mit.edu/barker/

Suggested fix:
Convert font-awesome to CDNs and add support for FA4.

FA3 CDN:

```
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
```

FA4 CDN (we need to sign up):
http://fontawesome.io/get-started/

Because of the syntax change between 3 and 4  (icon- prefix vs fa- prefix), we want to include both until we can convert over the icons in use, unless there is some problem with having both.

**Comment by PBruk** [comment]
Added FA4.3.0 CDN to Parent. 4.6.3 was not available (via signup). Addresses #122. Work completed. PR submitted.

**Comment by frrrances** [comment]
Here is the latest CDN: 
```
<script src="https://use.fontawesome.com/2873b047b1.js"></script> 
```
(I registered under web-lib)

**Comment by matt-bernhardt** [comment]
Is this still needed? The referenced URLs in the ticket itself don't seem to have any broken icons anymore.

**Comment by frrrances** [comment]
Well, we should probably thoroughly clean up our FA but yes it looks like this is no longer needed. I'll close it out.
