### ISSUE TITLE
hours.min.css stylesheet appearing twice

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITlibraries-parent#134]
Noticed that hours.min.css is being loaded twice. Possible other sheets, as well.

![page-hours](https://cloud.githubusercontent.com/assets/1832277/16088525/88938cc4-32f5-11e6-9dd1-638e0c0c159c.png)

**Comment by matt-bernhardt** [comment]
Good catch - this is loaded once by functions.php at 

https://github.com/MITLibraries/MITlibraries-parent/blob/prod/functions.php#L117

and again at

https://github.com/MITLibraries/MITlibraries-parent/blob/prod/page-hours-json.php#L36

There's a number of scripts that are loaded in `page-hours-json.php` that probably need to be instead loaded in `functions.php` via enqueue calls.
