### ISSUE TITLE
Search bar triggering insecure content warning

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITlibraries-parent#16]

**Comment by matt-bernhardt** [comment]
This is the warning as seen in Firefox. The scenario is that a secured front page is posting to an insecure target.
![insecure content warning](https://cloud.githubusercontent.com/assets/1403248/11666762/11a0c70e-9dbc-11e5-8634-2f8e2fcf0105.png)

**Comment by matt-bernhardt** [comment]
The discussion on pages like this:
http://stackoverflow.com/questions/2677570/how-to-post-data-to-an-http-page-from-an-https-page

indicates that this warning will always be seen when posting content from a secured page (i.e. our front page) to an unsecured page (which, unfortunately, is all of our discovery environment). 

There are some workarounds that we might explore, and I'm trying to put in place code to test them out. In the meantime, however, I'm not sure of the status of any of our discovery tools in their conversion to HTTPS. How can we compile this information?
