### ISSUE TITLE
Experts profile photo squished

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#167]
The profile photo is small or squished when there is a long job title. 

![boutin](https://cloud.githubusercontent.com/assets/4327102/17946793/d0a4a9ae-6a17-11e6-98e5-7a82a9b13d9e.jpg)

**Comment by PBruk** [comment]
Frances, I can't seem to recreate this problem and I don't see how it's possible looking at the code we have. There are other expert profiles that I see whose titles are just as long - or longer - and I don't see this happening... can you send me link, so I can take a look, please? Perhaps it's a browser issue, I wonder... pls don't tell me I.E.?

**Comment by frrrances** [comment]
@PBruk - I noticed that the image gets smaller (but not squished) in my FF.
