### ISSUE TITLE
Update footer text related to copyright

### ISSUE THREAD

**Issue by darcyduke** [MITLibraries/MITlibraries-parent#26]

**Comment by darcyduke** [comment]
Hi Phillip,

We need to edit the text in the footer of all our WP sites (although we can wait on the sites that will move to the child theme). All info is here, but let's talk before you tackle this: https://basecamp.com/2612667/projects/7659365/todolists/23550937 

I also noticed that the current copyright statement isn't formatted correctly on prod - it's pushed up against the logo - it should look more like the footer in LibGuides (see: https://libguides.mit.edu/rss).

**Comment by PBruk** [comment]
Updated in Footer.
