### ISSUE TITLE
Something in the stylesheets is breaking ordered lists in Firefox

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/MITlibraries-parent#27]
Here are two pages with ordered lists that currently display incorrectly:
https://libraries.mit.edu/study/reserve/
http://libraries.mit.edu/preserve/about/digital/digital-preservation-principles/

Viewed in Chrome, the lists on these pages are numbered correctly. In Firefox, however, they are all numbered "1.". 

When I disable all the theme-based stylesheets for these two pages, the numbers correct themselves. I have not yet identified specific rules that are causing the problem.

**Comment by matt-bernhardt** [comment]
IE and Opera also do not have this problem - only Firefox. Multiple people have reported seeing the FF behavior, so it does not appear to be just one user.

**Comment by PBruk** [comment]
Made adjustments in CSS/SCSS

**Comment by darcyduke** [comment]
Another example: https://libraries-test.mit.edu/preserve/about/digital/principles/
