### ISSUE TITLE
Problems with breakpoints on location pages

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITlibraries-parent#35]

**Comment by PBruk** [comment]
There are two (related) problems I have noticed:

The first is that the sidebar doesn't collapse at a proper breakpoint leaving this:
http://screencast.com/t/x0IJ6ZYnile

The second is that the two columns that make up the information for the locations pages also don't break/collapse properly. Here is a screenshot of the page on an Android phone at 600px:
http://screencast.com/t/sa7Psbp5TgUo

**Comment by darcyduke** [comment]
Phillip, I feel like we fixed this at some point and it must have somehow reverted?

**Comment by PBruk** [comment]
Also, look at Study Spaces page: responsive columns?

**Comment by PBruk** [comment]
This should be all set now.
