### ISSUE TITLE
Site-wide alert style looks funky on mobile

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#38]
The icon is very small and the title is very large, and it doesn't match the local (location) alert. I think the side-wide title can be much smaller on mobile and be a closer match to the local alert. Here's a screenshot: 

![img_3399](https://cloud.githubusercontent.com/assets/4327102/12300448/7fa7f9a4-b9e9-11e5-9e08-a7aebd2351da.PNG)

**Comment by matt-bernhardt** [comment]
This issue is somehow still on the Waffle board, but the commit that fixed it (ca41a34) has been merged. Is this a change we can / have tested? Can I close this?

**Comment by darcyduke** [comment]
Frances and I tested this and it's all good!
