### ISSUE TITLE
Remove UI control from home page that promises to promote experts to homepage

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#53]
When adding Nicholas Albaugh as an expert, it seemed like the Homepage featured experts was not respecting the Experts selection on the back end (Nicholas showed up before I selected him).

**Comment by matt-bernhardt** [comment]
Experts are loaded via the JSON API, from this URL: https://libraries.mit.edu/wp-json/posts?type=experts . The file that controls it is js/experts-home.js. 

How are experts 'selected' for promotion to the front page? Is it just a question of setting the post to "published"? Or is there another flag that I'm missing?

**Comment by frrrances** [comment]
@matt-bernhardt On the "Home" page, there is a multi-select box that is meant to select from the available experts. Let me know if you have any trouble finding that multi-select.

**Comment by matt-bernhardt** [comment]
As we discussed (I think in Slack), the script that loads the experts isn't currently configured to respect the selection of experts - so our route forward on this is to remove the UI control from the home page.

I'm working on this, but I'm not sure of what the actual change is going to end up being.

**Comment by matt-bernhardt** [comment]
It appears that this aspect of the home page edit screen is controlled by Custom Fields, so a code change wouldn't be needed. However, this function:

https://github.com/MITLibraries/MITlibraries-parent/blob/prod/functions.php#L708-L720

may also be related, and could be removed.

**Comment by matt-bernhardt** [comment]
I've got a deployable branch that will test the removal of getExperts() function, but in the meantime I've also removed most of the (probably unneeded) Custom Fields from the homepage. This has been done on -dev. 

If the front page behavior still seems okay, next step will be to remove the fields on -test and -test2. This can be something that is done independent of a code deploy.

**Comment by matt-bernhardt** [comment]
I'm marking this as closed. As a postscript, the actual fields themselves were removed by editing the "Home Page" fields set defined in the admin UI.
