### ISSUE TITLE
Add hidden context to Search nav

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#67]
To help make clear that the "Search" item in the main nav is a navigation menu, add hidden but accessible text to the nav: 

Reads: "Search navigation menu"
Displays: "Search" (no change from current"
Code: ``<a class="no-underline" href="/search">Search <span class="sr">navigation menu</span></a>``

(actual class for navigation should be whatever we are currently using to hide text meant for screen readers)

**Comment by PBruk** [comment]
Work completed, PR submitted.
