### ISSUE TITLE
Fix header of /about page

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITlibraries-parent#89]
The header breaks on mobile screens.

**Comment by PBruk** [comment]
@frrrances, this is a content issue. The "mission" paragraph and/or video, in the header, need to be wrapped in new divs/classes to fix the flow on mobile.

https://libraries-dev.mit.edu/about/

**Comment by frrrances** [comment]
Oh I actually changed this page on prod and it's working correctly there so i think we can close this. @PBruk can you just double check that what you filed the bug on is gone on prod?
https://libraries.mit.edu/about/

**Comment by PBruk** [comment]
I double-checked Prod and this looks solved, yes!
