### ISSUE TITLE
The hover on menu link is blue on certain sub-pages

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITlibraries-parent#94]
The main menu on library sub-pages, like /dewey/about, show #23527c on hover, unlike all other types of pages, it seems, which properly, show #fff.

**Comment by PBruk** [comment]
So this is happening because those pages have a submenu, which is created via the navwalker, which uses/imports bootstrap styling, not used elsewhere.

**Comment by PBruk** [comment]
Work completed. PR submitted.

**Comment by matt-bernhardt** [comment]
As a reminder, if you reference the issue number in your commit message on the relevant branch, the affiliation between this issue and the code change that fixes is is automatically recorded.
