### ISSUE TITLE
Fix MIT History slider image

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITlibraries-parent#96]
The image in the slider on the MIT History site is generated using an image resizer built into the theme that no longer works. 

We need to change the image to use more modern image resizer/cropper like news or just rely on a properly sized image in a custom field.

**Comment by matt-bernhardt** [comment]
Closing this issue here, and opening it against the MITHistory repo. This is issue #1 over at https://github.mit.edu/mitlibraries/mithistory/issues/1
